name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - infra/terraform/**

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        run: |
          aws configure set region "us-east-1"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy backend
        run: |
          terraform -chdir=infra/terraform init
          terraform -chdir=infra/terraform apply -auto-approve
