name: Verify Frontend Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  verify-frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci --prefix frontend

      - name: Build frontend
        env:
          VITE_COGNITO_USER_POOL_ID: ${{ vars.VITE_COGNITO_USER_POOL_ID }}
          VITE_COGNITO_USER_POOL_CLIENT_ID: ${{ vars.VITE_COGNITO_USER_POOL_CLIENT_ID }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        run: ./build.sh
